Describe REST API
afiskon/hurmadb pull request #2
Opened 2017-05-19 18:08 UTC by Alexey-N-Chernyshov

2017-05-27 04:50 UTC, Alexey-N-Chernyshov commented on API.md
> +  `PUT`
fixed

2017-05-27 04:54 UTC, Alexey-N-Chernyshov commented on API.md
> +
вавава

2017-05-29 09:51 UTC, afiskon requested changes

2017-05-29 09:51 UTC, afiskon commented on API.md
> +  `GET` | `PUT`
Actually GET /v1/_stop does nothing.

2017-05-29 09:51 UTC, afiskon commented on API.md
> +* **Sample Call:**
Better call it "Examples"

2017-05-29 09:51 UTC, afiskon commented on API.md
> +  * **Code:** `404` <br />
Actually 404 is not an error. It's a regular response that means that requested key doesn't exist.

2017-05-29 09:51 UTC, afiskon commented on API.md
> +* **Success Response:**
s/Success/Successful

2017-05-29 09:51 UTC, afiskon commented on API.md
> +  `GET` | `DELETE` | `PUT`
Well, in fact it's 3 separated requests. GET /v1/kv/some_key reads a value, DELETE deletes it and PUT creates or updates a value.

2017-05-30 07:57 UTC, Alexey-N-Chernyshov commented on API.md
> +  `GET` | `DELETE` | `PUT`
done

2017-05-30 07:57 UTC, Alexey-N-Chernyshov commented on API.md
> +* **Sample Call:**
done

2017-05-30 14:44 UTC, merged

2017-05-30 14:44 UTC, afiskon commented
LGTM. Merged. Thank you a lot!