Fixed clang-format supports v3.8
afiskon/hurmadb pull request #4
Opened 2017-06-01 15:23 UTC by Alexey-N-Chernyshov

I removed some more keys.

2017-06-02 12:33 UTC, afiskon requested changes

2017-06-02 12:33 UTC, afiskon commented on .clang-format
> -JavaScriptWrapImports: true
ОК, we don't need those

2017-06-02 12:33 UTC, afiskon commented on .clang-format
> -BreakAfterJavaFieldAnnotations: false
OK

2017-06-02 12:33 UTC, afiskon commented on .clang-format
> -BreakStringLiterals: true
OK

2017-06-02 12:33 UTC, afiskon commented on .clang-format
> -SpaceAfterTemplateKeyword: false
This one causes changes in defer.h shown below, but I don't mind.

2017-06-02 12:33 UTC, afiskon commented on src/HttpServer.cpp
> +                /* match! */
Are you sure this is a right formatting after running `make format` ? I have Clang 4.0.0 and it doesn't change this. What version of Clang are you using?

2017-06-02 12:33 UTC, afiskon commented on src/HttpServer.cpp
> +   */
Same question as above. That's just not very pretty. Perhaps you could rewrite it somehow to make your version of clang-format happy?

2017-06-02 12:33 UTC, afiskon commented on src/Socket.cpp
> +             * `nc` */
Meh... OK, I can live with that.

2017-06-03 11:22 UTC, Alexey-N-Chernyshov commented
My fault, comments were modified by the default style. I'll better create a new pull request to not show wrong commits in the history.

2017-06-03 11:22 UTC, closed without merging